config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CabinetMedical</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/header' %>
    <%= render 'shared/flashes' %>

    <%= yield %>

  </body>
    
    <%#= render 'shared/footer' %>
</html>

app/views/pages/home.html.erb
<section>
  <div class="banner" style="background-image: url(<%= image_path 'banner.jpg'%>);">
    <div class="container">
      <div class="about">
        <div class="about-content">
          <div class="col md-6">       
          <h1 class="h2 mt-4 mb-4 ">Cabinet Medical</h1>
            <div class="column-left">
              <p>Le Docteur Lucienne Ramaroson vous reçoit dans son cabinet à Mérignac pour des consultations en médecine générale.
               Consultations en urgence dans la journée possibles après accord téléphonique du Dr Lucienne Ramaroson.</p> 
              
              <h2 class="h2 mt-4 mb-4">Horaire</h2>
              <table class="table table-striped pl-4">
                <thead>
                  <tr>
                    <th scope="col"></th>
                    <th scope="col">Mardi</th> 
                    <th scope="col">Mercredi</th>
                    <th scope="col">Vendredi</th>
                    <th scope="col"></th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <th scope="col">Ouvert</th>
                    <th scope="col">17h</th>
                    <th scope="col">16h</th>
                    <th scope="col">16h</th>
                  </tr>
                </tbody>
                <tbody>
                  <tr>
                    <th scope="col">Fermer</th>
                    <th scope="col">20h</th>
                    <th scope="col">20h</th>
                    <th scope="col">20h</th>
                  </tr>
                </tbody>
              </table>
            </div>  
          </div>
          <div class="col md-6">
            <div class="column-right mb-4">
              <%= image_tag 'Cabinet.png',class:'img-project' %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-12 text-center-left">
      <h2 class="h2 mt-4">Activité</h2>
      <p>Le Docteur Lucienne Ramaroson vous reçoit le mardi, le mercredi et le vendredi de 16h30 à 20h. Les consultations se font sur RDV exclusivement.
      </p>      
      <h2 class="h2 mt-4 mb-4" id="tarif">Honoraires</h2>
        <table class="table table-striped text-center">
          <thead>
            <tr>
              <th scope="col"></th>
              <th scope="col">Consultation</th> 
            </tr>
          </thead>
          <tbody>
            <tr>
              <th scope="col">Enfant *</th>
              <th scope="col">25€</th>
            </tr>
          </tbody>
          <tbody>
            <tr>
              <th scope="col">Adulte *</th>
              <th scope="col">25€</th>            
            </tr>
          </tbody>
        </table>
        <p class="text-center">* Pour une personne, Mode paiement accepter: Espèce ou chéque.</p>
      </div>
      <main role="main" class="main-banner" id="blog-banner">
        <div class="container mt-5 mb-4">
          <h2 class="h2" id="contact">Contact</h2>
        </div>
      </main>
      <div class="container mb-5">
        <div class="row">
          <div class="col-md-8">
            <p>Vous pouvez prendre RDV par téléphone ou réservez un créneau via le bouton "Prendre rendez-vous" en haut de la page.</p>
            <div class="row mt-5">
              <div class="col-md-6 col-xl-5">
                <p class="h4"><i class="fab fa-twitter text-info mr-2"></i> Telephone</p>
                <p><span>06 84 05 43 11</span></p>
                <p class="h4 mt-5"><i class="fas fa-envelope text-alert mr-2"></i> En voiture</p>
                <p>parking 3 places <span>(voir acces)</span> </p>
              </div>
              <div class="col-md-6 col-xl-5">
                <p class="h4"><i class="fab fa-facebook text-primary mr-2"></i> Localisation</p>
                <p>188 avenue de l'argonne Beutre 33700 Mérignac</p>
                <p class="h4 mt-5"><i class="fab fa-instagram text-warning mr-2"></i> En bus</p>
                <p>N°30-Arret :"Oscar Oriac" </p>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <iframe class="sm-lg-3 mt-3" width="300" height="300" id= "map" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?key=AIzaSyBwOWZ_C1sw6lYJhxYk_LJJCI2uM9GW8IA&q=220 avenue de l'argonne,merignac,bordeaux,france " allowfullscreen></iframe>
          </div>
        </div>
      </div>
    </div>
    <%= render 'shared/header-footer' %>
  </div>
</section>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: url(https://image.freepik.com/vecteurs-libre/contexte-sante-symboles-medicaux-dans-cadre-hexagonal_1017-26363.jpg);">
  <div class="container">
    <h1>Le Wagon brings <strong>tech skills</strong> to <strong>creative people</strong>!</h1>
    <p>Change your life and learn to code at one of our campuses around the world.</p>
    <a class="btn btn-flat" href="#">Apply now</a>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_header-footer.html.erb
<div class="header-footer">
  <div class="header-footer-infos">
    <div class="row">
      <div class="col-md-8 w-100">
        <h2>Cette application est gratuit, indépendant.</h2>
      </div>
      <div class="col-md-4 w-100 ">
        <h2>Dr L. Ramaroson, Généraliste</h2>
      </div>
    </div>
  </div> 
</div>

app/views/shared/_header.html.erb
<div class="header-navbar">
  <div class="header-navbar-infos">
    <div class="row">
      <div class="col-12">
        <h2>Vous pouvez me joindre au 06.84.05.43.11. En cas urgence, veuiller contacter le 15 </h2>
      </div>   
    </div>
  </div> 
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/",id: "icon", class: "navbar-brand" do %>
    <%= image_tag "logo.png", class:"logo" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Home", "#", class: "nav-link btn btn-ghost mt-1" %>
      </li>
      <li class="nav-item">
        <%= link_to "Contact","#contact", class: "nav-link btn btn-ghost mt-1" %>
      </li>
      <li class="nav-item">
        <%= link_to "Legal","#", class: "nav-link btn btn-ghost mt-1" %>
      </li>
      <li class="nav-item">
        <button type="button" class="btn btn-ghost mt-1" data-toggle="modal" data-target="#registerModal">
            Register
        </button>
        <button type="button" class="btn btn-ghost mt-1" data-toggle="modal" data-target="#loginModal">
            Login
        </button>
      </li>
      <% if user_signed_in?%>
        <li class="nav-item">
          <%= link_to "Home", "#", class: "nav-link btn btn-ghost mt-1" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact","#contact", class: "nav-link btn btn-ghost mt-1" %>
        </li>
        <li class="nav-item">
          <%= link_to "Legal","#", class: "nav-link btn btn-ghost mt-1" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link btn btn-ghost mt-1" %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="modal fade" id="registerModal" tabindex="-1" aria-labelledby="registerModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header" style="background-color: #bcf1c3; color: white">
          <h5 class="modal-title" id="registerModalLabel">Registration</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="color: white">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= simple_form_for(User.new, as: :user, url: registration_path(:user)) do |f| %>
            <%= f.error_notification %>
            <div class="form-inputs">
              <%= f.input :email,
                        required: true,
                        autofocus: false,
                        input_html: { autocomplete: "email" }%>
              <%= f.input :password,
                        required: false,
                        hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                        input_html: { autocomplete: "new-password" } %>
              <%= f.input :password_confirmation,
                        required: true,
                        input_html: { autocomplete: "new-password" } %>
            </div>
          </div>
          <div class="modal-footer" style="background-color: #bcf1c3; color: white">
            <div class="form-actions">
              <button type="button" class="btn btn-ghost bg-white " data-dismiss="modal">Close</button>
              <%= f.button :submit, "Sign up", class: "btn btn-ghost bg-white" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header" style="background-color: #bcf1c3; color: white">
          <h5 class="modal-title" id="loginModalLabel">Registration</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="color: white">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= simple_form_for(User.new, as: :user, url: session_path(:user)) do |f| %>
            <div class="form-inputs">
              <%= f.input :email,
                        required: false,
                        autofocus: true,
                        input_html: { autocomplete: "email" } %>
              <%= f.input :password,
                        required: false,
                        input_html: { autocomplete: "current-password" } %>
              <%= f.input :remember_me, as: :boolean %>
            </div>
          </div>
          <div class="modal-footer" style="background-color: #bcf1c3; color: white">
            <div class="form-actions">
              <button type="button" class="btn btn-ghost bg-white" data-dismiss="modal">Close</button>
              <%= f.button :submit, "Login", class: "btn btn-ghost bg-white" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>